export const storyContent = {
  hero: {
    badge: 'Enterprise Bank Reconciliation',
    headline: 'Stop searching for the right ledger.',
    subheadline: 'RecoBit eliminates up to 80% of manual reconciliation overhead by automating statement ingestion, intelligent ledger mapping, and ERP sync.',
    primaryCta: 'See How RecoBit Works',
    secondaryCta: 'Book Enterprise Demo',
    stats: [
      { value: '85–95%', label: 'Reduction in reconciliation time' },
      { value: '99%', label: 'AI matching confidence' },
      { value: '1-Click', label: 'Direct ERP ledger sync' },
    ],
  },
  scene02ManualSearch: {
    badge: 'The Daily Struggle',
    tag: 'SCENE 01 / THE BOTTLENECK',
    title: 'Searching 3,000+ ledgers for one cryptic transaction.',
    body: 'A single transaction arrives: "UPI/394805395421/HDFC/SHREE COLLECTION/Cs". To post it correctly, an accountant must scroll, search, guess, and verify across endless chart of accounts. Multiply this by hundreds of daily transactions, and days disappear.',
    searchSimulation: {
      query: 'SHREE COLL',
      totalCandidates: 3412,
      confusingOptions: [
        { code: 'L-0842', name: 'Shree Collection Traders Pvt Ltd (Pune)', match: '62%' },
        { code: 'L-1190', name: 'Shree Collections Retail A/C (Nagpur)', match: '58%' },
        { code: 'L-2451', name: 'Shree Krishna Collections (Bhandara)', match: '45%' },
        { code: 'L-3012', name: 'Shree Laxmi Collection Agency', match: '34%' },
        { code: 'L-0104', name: 'Shree Ram Collection Account', match: '28%' },
      ],
    },
  },
  scene03Import: {
    badge: 'Data Friction',
    tag: 'SCENE 02 / FORMAT CHAOS',
    title: 'Statement formats change. The manual prep never stops.',
    body: 'PDFs with complex headers, multi-sheet Excel files, password-protected statements, mismatched columns. Accountants spend hours reformatting data before reconciliation even begins.',
  },
  scene04Pivot: {
    badge: 'The Paradigm Shift',
    tag: 'SCENE 03 / THE TURNING POINT',
    quote: 'What if your system already understood your banking patterns before you typed a single letter?',
    subtext: 'RecoBit enters the workflow. Chaos crystallizes into intelligent order.',
  },
  scene05Top10: {
    badge: 'Intelligent Auto-Mapping',
    tag: 'SCENE 04 / SMART BATCH MAPPER',
    title: 'From infinite search to Top 10 High-Confidence Picks.',
    body: 'RecoBit parses messy transaction narrations, extracts payment identifiers, and surfaces the top 10 most probable ledger matches. One click confirms. Zero ledger hunting.',
    sampleTransaction: {
      date: '30/05/2026',
      narration: 'UPI 394805395421/HDFC/SHREE COLLECTION/Cs',
      amount: '₹20,000.00',
      type: 'RECEIPT',
      vchNo: '394805395421',
      topPicks: [
        { rank: 1, name: 'Shree Collection - Nagpur Depot', confidence: '99%', reason: 'Historical UPI Vch pattern match' },
        { rank: 2, name: 'Shree Collection Wholesale A/C', confidence: '84%', reason: 'Frequent HDFC counterparty' },
        { rank: 3, name: 'Shree Collection Current A/c (Bhandara)', confidence: '71%', reason: 'Regional branch alignment' },
        { rank: 4, name: 'Shree Collection Sales Ledger', confidence: '63%', reason: 'General receipt mapping' },
      ],
    },
  },
  scene06Scale: {
    badge: 'Workload Velocity',
    tag: 'SCENE 05 / HIGH VOLUME',
    title: 'From 1 transaction to 10,000+ without fatigue.',
    body: 'Whether processing 50 transactions or 50,000 across multiple bank accounts, RecoBit scales effortlessly. Batch mapping reduces full days of tedious ledger entry into a 10-minute review session.',
  },
  scene07Reconciliation: {
    badge: 'The Core Platform Engine',
    tag: 'SCENE 06 / HYBRID MATCHING',
    title: 'Two worlds aligned: Bank Statement vs ERP Books.',
    body: 'RecoBit pairs deterministic mathematical rules with semantic AI to reconcile your actual bank feed against general ledger vouchers in Tally Prime, SAP, or your enterprise ERP.',
    categories: [
      { id: 'matched', label: 'Matched', count: 262, color: 'green', desc: 'Exact date, amount, and reference alignment' },
      { id: 'unmatched', label: 'Unmatched', count: 126, color: 'orange', desc: 'Items with minor narration or date variance' },
      { id: 'missing_books', label: 'Missing in Books', count: 0, color: 'gray', desc: 'Direct bank transactions not yet posted in ERP' },
      { id: 'missing_statement', label: 'Missing in Statement', count: 5, color: 'amber', desc: 'Uncleared cheques or pending vouchers' },
      { id: 'bank_charges', label: 'Bank Charges', count: 71, color: 'blue', desc: 'Automated SMS, tax, and folio fee categorization' },
    ],
  },
  scene09BulkExceptions: {
    badge: 'Exception Handling',
    tag: 'SCENE 07 / THE NEW WORKFLOW',
    title: 'Stop checking everything. Focus only on exceptions.',
    body: 'Your role shifts from tedious manual search to high-leverage review. RecoBit automatically groups date, amount, and narration variances. Apply bulk resolutions to dozens of records in a single click.',
    groups: [
      { title: 'Narration Mismatch (96)', impact: '96 records', action: 'Bulk Resolve via AI Match' },
      { title: 'Date Drift within 48h (18)', impact: '18 records', action: 'Bulk Approve Clearing Date' },
      { title: 'Standard Bank Charges (71)', impact: '71 records', action: 'Auto-Post to Bank Charges Ledger' },
    ],
  },
  scene10Finalize: {
    badge: 'Direct ERP Posting',
    tag: 'SCENE 08 / SEAMLESS PUSH',
    title: 'One click to finalize. Instant sync to Tally / ERP.',
    body: 'With all exceptions resolved, finalize the session. Verified ledger entries push directly to your ERP via RecoBit’s secure Rust agent. Full session snapshots are permanently logged for audit peace of mind.',
  },
  scene11Dashboard: {
    badge: 'Operational Command',
    tag: 'SCENE 09 / CENTRAL VISIBILITY',
    title: 'Complete clarity across all banks, ledgers, and closing metrics.',
    body: 'Unified visibility into all bank accounts, Dr/Cr opening and closing balances, matching velocity, and real-time team productivity.',
  },
  scene12Access: {
    badge: 'Enterprise Governance',
    tag: 'SCENE 10 / MAKER-CHECKER SECURITY',
    title: 'Multi-role governance with strict Maker-Checker controls.',
    body: 'Role-based access control separates operational work from ERP push authority. Owners and Admin Checkers oversee reconciliation pipelines while User Makers prepare mappings safely.',
    roles: [
      { title: 'Owner Admin', badge: 'Full Authority', desc: 'Workspace creator, admin management, and enterprise settings.' },
      { title: 'Admin (Checker)', badge: 'Authorizing Privilege', desc: 'Approves final reconciliation sessions and ERP postings.' },
      { title: 'User (Maker)', badge: 'Draft & Map Privilege', desc: 'Performs statement uploads, ledger mapping, and exception triage.' },
    ],
  },
  scene13AiAgent: {
    badge: 'Financial Intelligence',
    tag: 'SCENE 11 / CONTEXT-AWARE AI',
    title: 'Ask your financial data anything. Get instant answers.',
    body: 'Not a generic chatbot. RecoBit’s AI Agent analyzes your live chart of accounts, bank balances, reconciliation logs, and party metrics to return instant contextual business answers.',
    samplePrompts: [
      {
        q: 'Provide me all the ledgers present under Bank Account Groups',
        a: 'The active ledgers under Bank Account Groups for NITIN MARKETING SERVICES PVT. LTD. are:\n• Bank of Maharashtra Nagpur A/c No 60436409318 (CSR)\n• Bank of Maharashtra Nagpur A/c No 60305166124\n• Bank of Maharashtra Bhandara A/c No. 60306124751\n• CITI BANK CA A/C NO. 0007320629',
      },
      {
        q: 'Which parties have the highest unmapped transaction volume this month?',
        a: 'Analysis of May 2026 statements:\n1. Coromandel International (₹1.25 Cr) — AI Suggested Match: Coromandel Pune\n2. Daftari Agro Pvt Ltd (₹41.00 L) — AI Suggested Match: Daftari Agro Wardha\n3. Mahindra Agri Solutions (₹31.50 L) — AI Suggested Match: Mahindra Agri Mumbai',
      },
    ],
  },
  scene14Trust: {
    badge: 'Auditability & Compliance',
    tag: 'SCENE 12 / IMMUTABLE TRACEABILITY',
    title: 'Every action is accounted for. Nothing disappears.',
    body: 'From statement ingestion and AI match suggestions to manual overrides, checker approvals, and ERP voucher IDs, every single change maintains an immutable timestamped audit trail.',
    timeline: [
      { step: '01', title: 'Statement Ingestion', detail: 'Cryptographic hash logged; raw source preserved' },
      { step: '02', title: 'AI Match & Score', detail: 'Hybrid engine logs 99% match rationale' },
      { step: '03', title: 'User Review & Override', detail: 'Maker adjustment recorded with user timestamp' },
      { step: '04', title: 'Checker Approval', detail: 'Admin verifies balance and authorizes voucher push' },
      { step: '05', title: 'ERP Push Confirmation', detail: 'Permanent ERP voucher number (e.g. BRN0426/2578) assigned' },
    ],
  },
  scene15Cta: {
    badge: 'Ready to Transform Your Close?',
    headline: 'Stop searching. Start reconciling in minutes.',
    subheadline: 'Join modern finance and accounting teams who save 85%+ of their reconciliation time with RecoBit.',
    primaryButton: 'Schedule an Enterprise Walkthrough',
    secondaryButton: 'Explore Documentation',
    benefits: [
      'No ERP code changes required',
      'Secure on-premise Rust agent',
      'Free pilot on your actual bank data',
    ],
  },
  footer: {
    copyright: '© 2026 RecoBit Technologies Inc. All rights reserved.',
    tagline: 'AI-Powered Enterprise Bank Reconciliation & Ledger Automation.',
    links: [
      { label: 'Product Architecture', href: '#reconciliation' },
      { label: 'Smart Batch Mapper', href: '#matching' },
      { label: 'Security & Governance', href: '#governance' },
      { label: 'AI Financial Agent', href: '#ai-agent' },
      { label: 'Enterprise Contact', href: '#cta' },
    ],
  },
} as const;
